#!/bin/bash

#
#
#
#
#

# Global variables
logFile="deploy.log"

# Clean the old log file
if [ -e $logFile ]; then
    rm -rf $logFile
fi

# Check if the script has been run as root user
if [ $USER != "root" ]; then
    echo "Error: Script must be run as root user." >> $logFile
    exit 1
fi

# Source the function.sh to have access to commonly used functions
if [ ! -e functions.sh ]; then
    echo "Error: Unable to find functions.sh. Please make sure you have downloaded all the necessary files." >> $logFile
    exit 2
else
    source functions.sh
    if [ $? -ne 0 ]; then
        echo "Error: Unable to source functions.sh file." >> $logFile
        exit 3
    fi
fi

# In case configure is called with the help parameter show the help file
if [ "$1" == "--help" ] ||  [ "$1" == "help" ]; then
    cat help | grep "# Deploy" -A 16 -B 1
    exit 0
fi

# Read parameters
while getopts c: option; do
    case "${option}" in
        C) clientApp=${OPTARG};;        # currently supports roundcube and squirrel
       
    esac
done

# Check the distro we are running on
GetDistro

if [[ "$DISTRO" == "ubuntu"* ]]; then
    LogMessage "Info: $DISTRO distribution detected." $logFile
    LogMessage "Info: Proceeding to package installation." $logFile

    apt-get update
    apt-get install -y bind9 dnsutils apache2 php5 postfix dovecot-common dovecot-imapd dovecot-pop3d
    
    
fi

if [[ "$DISTRO" == "centos"* ]]; then
    LogMessage "Info: $DISTRO distribution detected." $logFile
    LogMessage "Info: Proceeding to package installation." $logFile
fi
